### ISSUE TITLE
Discuss the importance of Ecto migrations for ecto_mnesia

### ISSUE THREAD

**Issue by josevalim** [Nebo15/ecto_mnesia#53]
Hi @AndrewDryga, 

Apologies if this is not the correct place for this but I would like to ask how important is migrations for ecto_mnesia. We are discussing the possibility of creating ecto_sql, to keep Ecto core small, and I am wondering if migrations should be moved to ecto_sql or be kept in the main Ecto repo.

I am thinking that for databases like Mnesia and Mongo, running user scripts as migrations, is more productive than hiding it behind a DSL but I would love your feedback on it.

**Comment by AndrewDryga** [comment]
Hello @josevalim,

Personally, I don't see this adapter as used for a long term in production. I see it more as a temporary solution so you can work with Elixir and Ecto without bothering too much about deploying and/or installing dependencies, especially when you doing something simple. (There are some other use cases though, like embedded software and when you need very low latency.)

So I like the idea to have migrations because it makes Mnesia adapter closer to a "drop-in replacement" for any other, it would require less work to migrate from this adapter to PostgreSQL. Also, for beginners, we don't need a separate guide how to migrate the database. 

I am perfectly fine to drop them and would support any your decision. We can write a similar DSL (but without types) or guides for Mnesia. And it's not that bad to write migrations whenever you would migrate a storage, because data may need a migration too.

Regarding moving SQL stuff to ecto_sql, I must say that Ecto by itself is not very good for NoSQL things, at least I don't imagine myself using it in large production with anything except PostgreSQL or MySQL at the moment. I know that few guys are working on Cassandra adapter, and it would be pretty much as SQL-one except syntax limitations and sharing features. (CQL looks pretty close to SQL for me.) And by looking at the list in Ecto readme, Mnesia is the only one that supports Ecto 2.0. So does it really work the effort to move away something that can be used in the majority of adapters?

**Comment by josevalim** [comment]
@AndrewDryga the thing is that people want to use Ecto even without a database and removing the ecto_sql stuff is a good boundary for that. :) Maybe we should have both ecto_migration and ecto_sql.

**Comment by AndrewDryga** [comment]
@josevalim nothing stops ecto_mnesia from depending on ecto_sql. Of course, we won't need most of it, but it's not the most important concern at the moment :).

**Comment by AndrewDryga** [comment]
I'm closing this because there is no active discussion any more.

**Comment by josevalim** [comment]
Yes, apologies for not closing it. :)
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
