### ISSUE TITLE
Unique index , associations and :in query clausal

### ISSUE THREAD

**Issue by EnriqueAldana** [Nebo15/ecto_mnesia#54]
I am using Mnesia adapter but it does not support:
Unique/all other constraints (including associations) and :in query clausule

Let me give you a vote to take importance to development this features.
Regards
Jesus Enrique Aldana Sanchez

**Comment by AndrewDryga** [comment]
Hello @EnriqueAldana. Unfortunately, we do not accept feature requests in form of issues. I only have time to concentrate on whatever is already implemented, just because It allows the adapter to stay a simple abstraction on top of Mnesia. However, contributions are welcomed and if someone what's to implement the feature, I'd be more than happy to mentor and merge the PR :).

I believe `in` should be supported, it's converted to multiple `or` clauses underneath. Native `in`'s are possible with QLC, but using QLC instead of MatchSpec's would be a pretty hard task.
